ALTER TABLE "profiles"
ADD COLUMN IF NOT EXISTS "dataset" TEXT NOT NULL DEFAULT 'v1';

ALTER TABLE "profiles"
ADD COLUMN IF NOT EXISTS "country_name" TEXT NOT NULL DEFAULT '';

ALTER TABLE "profiles"
ALTER COLUMN "country_id" TYPE VARCHAR(2);
